# Generated by Django 4.2.6 on 2024-02-27 12:56

from django.db import migrations
import src.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=src.base.fields.WEBPField(upload_to='brands', verbose_name='Image'),
        ),
    ]
