# Generated by Django 4.2.6 on 2024-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='medium_square_crop',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brands', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='medium_square_crop',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Medium square crop'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
