# Generated by Django 4.2.6 on 2024-02-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_part_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description_uz',
        ),
    ]
